# ^ BASICS: Main flow that will call a reusable flow
name: Manual Trigger Test
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - feat/basics
  # pull_request:
  #   types: [opened, synchronize, reopened]


jobs:
  job1:
    name: Call Reusable Workflow
    # uses: <path of the file we want to use>
    uses: gisaacsotelo/reusable-workflows/.github/workflows/basics-data.yml@main
    # with: <inputs required for the flow to work>
    with:
      str_input: "This is my input string"

    # secrets:
      # Add secrets here if required
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # AZURE_ARTIFACTS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_TOKEN }}   