# ^ BASICS: Share data between Jobs and Steps
name: Basics
on:
  workflow_call:
    inputs:
      str_input:
        description: 'String'
        required: true
        type: string
      # stringified_JSON:
      #   description: 'Stringified JSON'
      #   required: true
        # type: string
    # secrets:
    #   SONAR_TOKEN:
    #     required: true
    #   AZURE_ARTIFACTS_TOKEN:
    #     required: true  

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    outputs:
      # $ variable_name: ${{ steps.[step_id].outputs.[output_name] }}
      job1_output: ${{ steps.step1.outputs.step_output }}
    steps:

      - name: Step 1
        id: step1
        run: |
          echo "---------------------------------------"
          echo "----------------- INPUTS --------------"
          echo "Input recieved: ${{ inputs.str_input }}"
          echo "---------------------------------------"
          echo "Declaring outputs:"
          echo "step_output=${{ inputs.str_input}}" >> $GITHUB_OUTPUT
          echo "---------------------------------------"
          echo "Print from output stored variable"
          echo "Step Output: ${{ steps.step1.outputs.step_output }}"
          echo "From variable same step: $step_output"
          echo "---------------------------------------"

      
      - name: Step 2 - Manipulation & Outputs
        run: |
          echo "---------------------------------------"
          echo "Step Output: ${{ steps.step1.outputs.step_output }}"
          echo "---------------------------------------"


  job2:
    runs-on: ubuntu-latest
    name: job2
    needs: job1
    steps:

      - name: Step1 - Job2
        run: |
          echo "P2: ${{ needs.job1.outputs.step_output }}"