# ^ BASICS: Share data between Jobs and Steps
name: Basics
on:
  workflow_call:
    inputs:
      str_input:
        description: 'Input String'
        required: true
        type: string
      # stringified_JSON:
      #   description: 'Stringified JSON'
      #   required: true
        # type: string
    # secrets:
    #   SONAR_TOKEN:
    #     required: true
    #   AZURE_ARTIFACTS_TOKEN:
    #     required: true  

jobs:
  job1:
    name: Label - job1
    runs-on: ubuntu-latest
    outputs:
      # $ variable_name: ${{ steps.[step_id].outputs.[output_name] }}
      job1_output: ${{ steps.step1.outputs.step_output }}
    steps:
      - name: Label - Step 1
        id: step1
        run: |
          echo "---------------------------------------"
          echo "----------------- INPUTS --------------"
          echo "Input recieved: ${{ inputs.str_input }}"
          echo "---------------------------------------"
          echo "Creating a variable..."
          data_variable='This is my data variable'
          echo "Declaring outputs..."
          echo "step_output=${{ inputs.str_input }}" >> $GITHUB_OUTPUT
          echo "---------------------------------------"
          echo "Print variable"
          echo "Variable: $data_variable"
          # ~ echo "Test comment Print - Variable: $data_variable"
          echo "Print from output stored variable"
          echo "Step Output: ${{ steps.step1.outputs.step_output }}"
          echo "From variable same step: $step_output"
          echo "---------------------------------------"

      
      - name: Label - Step 2 - Manipulation & Outputs
        run: |
          echo "---------------------------------------"
          echo "Variable: $data_variable"
          echo "Step Output: ${{ steps.step1.outputs.step_output }}"
          echo "---------------------------------------"

  job2:
    name: Label - job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Job 2
        run: |
          echo "P2: ${{ needs.job1.outputs.step_output }}"