# REUSABLE WORKFLOW

name: SonarScan
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      solution-matrix:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      p0: ${{ steps.setup.outputs.p0}}
      p1: ${{ steps.setup.outputs.p1}}
      p2: ${{ steps.setup.outputs.p2}}
    steps:
      - name: Step1-Print
        id: setup
        run: |
          echo "----------------- INPUTS --------------"
          echo "---------------------------------------"
          echo "Print Path Input: ${{ inputs.path }}"  
          echo "---------------------------------------"
          echo "Print Solution Matrix: ${{ inputs.solution-matrix }}"  
          echo "---------------------------------------"
          echo "---------------------------------------"
          p_0="$(echo ${{ inputs.path }} | cut -d'/' -f1)"
          echo "Print P0: ${p_0}"
          p_1="$(echo ${{ inputs.path }} | cut -d'/' -f2)"
          echo "Print P0: ${p_0}"
          p_2="$(echo ${{ inputs.path }} | cut -d'/' -f3)"
          echo "Print P0: ${p_0}"
          echo "---------------------------------------"
          echo "p0=${p_0}" >> $ GITHUB_OUTPUT
          echo "p1=${p_1}" >> $ GITHUB_OUTPUT
          echo "p2=${p_2}" >> $ GITHUB_OUTPUT
          echo "---------------------------------------"

  job2:
    name: jobo
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution: ${{ fromJSON(inputs.solution-matrix) }}
    steps:
      - name:
        run: |
          echo "---------------------------------------"
          echo "Print P0: ${{ needs.setup.outputs.p0 }}"
          echo "Print P1: ${{ needs.setup.outputs.p1 }}"
          echo "Print P2: ${{ needs.setup.outputs.p2 }}"
          echo "Current iteration: ${{ matrix.solution }}"
          echo "---------------------------------------"


