# REUSABLE WORKFLOW

name: SonarScan
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      solution-matrix:
        required: true
        type: string

jobs:
  setup-job:
    runs-on: ubuntu-latest
    outputs:
      path0: ${{ steps.setup-step.outputs.p0}}
      path1: ${{ steps.setup-step.outputs.p1}}
      path2: ${{ steps.setup-step.outputs.p2}}
    steps:
      - name: Setup Data for Scan
        id: setup-step
        run: |
          echo "----------------- INPUTS --------------"
          echo "---------------------------------------"
          echo "Print Path Input: ${{ inputs.path }}"  
          echo "---------------------------------------"
          echo "Print Solution Matrix: ${{ inputs.solution-matrix }}"  
          echo "---------------------------------------"
          echo "---------------------------------------"
          p_0="$(echo ${{ inputs.path }} | cut -d'/' -f1)"
          echo "Print P0: ${p_0}"
          p_1="$(echo ${{ inputs.path }} | cut -d'/' -f2)"
          echo "Print P1: ${p_1}"
          p_2="$(echo ${{ inputs.path }} | cut -d'/' -f3)"
          echo "Print P2: ${p_2}"
          echo "---------------------------------------"
          echo "p0=${p_0}" >> $ GITHUB_OUTPUT
          echo "p1=${p_1}" >> $ GITHUB_OUTPUT
          echo "p2=${p_2}" >> $ GITHUB_OUTPUT
          echo "---------------------------------------"

  job2:
    name: jobo
    needs: setup-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution: ${{ fromJSON(inputs.solution-matrix) }}
    steps:
      - name:
        run: |
          echo "---------------------------------------"
          echo "Print P0: ${{ needs.setup-job.outputs.path0 }}"
          echo "Print P1: ${{ needs.setup-job.outputs.path1 }}"
          echo "Print P2: ${{ needs.setup-job.outputs.path2 }}"
          echo "Current iteration: ${{ matrix.solution }}"
          echo "---------------------------------------"


