# REUSABLE WORKFLOW
# Sending data between steps and string manipulation

name: Main-flow
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string


jobs:
  job1:
    name: setup-data
    runs-on: ubuntu-latest
    outputs:
      # $ variable_name: ${{ steps.[step_id].outputs.[output_name] }} 
      ROOT_OUTPUT: ${{ steps.data-outputs.outputs.root-output }}
      PROJECT_OUTPUT: ${{ steps.data-outputs.outputs.project-output }}
      SOLUTION_OUTPUT: ${{ steps.data-outputs.outputs.solution-output }}
      
    steps:
    - name: get-input
      id: get-input
      run: |
        echo "--------------------------------------"
        echo "PRINT STRING"
        echo "--------------------------------------"
        echo "input: ${{ inputs.path }}"
    
    - name: string-manipulation
      id: string-manipulation
      run: |
        echo "--------------------------------------"
        echo "DIVIDE STRING"
        echo "--------------------------------------"
        echo "Using cut method by each '/'"
        myRootDir="$(echo ${{ inputs.path }} | cut -d'/' -f1)"
        myProjectDir="$(echo ${{ inputs.path }} | cut -d'/' -f2)"
        mySolutionDir="$(echo ${{ inputs.path }} | cut -d'/' -f3)"
        echo "Root: ${myRootDir}"
        echo "--------------------------------------"
        echo "PRINT STRING"
        echo "--------------------------------------"
        echo "input: ${{ inputs.path }}"
        echo "Root: ${myRootDir}"
        echo "Project: ${myProjectDir}"
        echo "Solution: ${mySolutionDir}"

    - name: set-outputs
      id: data-outputs
      run: |
        echo "--------------------------------------"
        echo "DIVIDE STRING"
        echo "--------------------------------------"
        echo "Using cut method by each '/'"
        echo "myRootDir="$(echo ${{ inputs.path }} | cut -d'/' -f1)"" >> $GITHUB_OUTPUT
        myProjectDir="$(echo ${{ inputs.path }} | cut -d'/' -f2)" >> $GITHUB_OUTPUT
        mySolutionDir="$(echo ${{ inputs.path }} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
        echo "--------------------------------------"
        echo "PRINT FROM OUTPUTS - SAME JOB"
        echo "--------------------------------------"
        echo "Root: ${{ needs.job1.outputs.ROOT_OUTPUT }}"

