# REUSABLE WORKFLOW
# Sending data between steps and string manipulation

name: Main-flow
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string


jobs:
  job1:
    name: setup-data
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT

      - id: step2
        run: |
          echo "test=Perri" >> $GITHUB_OUTPUT
          echo "Output: ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}"

  job2:
    needs: job1
    name: setup-data
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
        echo "Output: ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}"



    # - name: string-manipulation
    #   id: string-manipulation
    #   run: |
    #     echo "--------------------------------------"
    #     echo "DIVIDE STRING"
    #     echo "--------------------------------------"
    #     echo "Using cut method by each '/'"
    #     myRootDir="$(echo ${{ inputs.path }} | cut -d'/' -f1)"
    #     myProjectDir="$(echo ${{ inputs.path }} | cut -d'/' -f2)"
    #     mySolutionDir="$(echo ${{ inputs.path }} | cut -d'/' -f3)"
    #     echo "Root: ${myRootDir}"
    #     echo "--------------------------------------"
    #     echo "PRINT STRING"
    #     echo "--------------------------------------"
    #     echo "input: ${{ inputs.path }}"
    #     echo "Root: ${myRootDir}"
    #     echo "Project: ${myProjectDir}"
    #     echo "Solution: ${mySolutionDir}"

    # - name: set-outputs
    #   id: data-outputs
    #   run: |
    #     echo "--------------------------------------"
    #     echo "DIVIDE STRING"
    #     echo "--------------------------------------"
    #     echo "Using cut method by each '/'"
    #     echo "root-output=$(echo ${{ inputs.path }} | cut -d'/' -f1) >> $GITHUB_OUTPUT
        
    #     project_dir_input="$(echo ${{ inputs.path }} | cut -d'/' -f2)" >> $GITHUB_OUTPUT
    #     solution_dir_input="${}echo ${{ input.path}} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
    #     echo "project_dir_input (var): ${project_dir_input}"
    #     echo "project_output=${project_dir_input}" >> $GITHUB_OUTPUT
    #     mySolutionDir="$(echo ${{ inputs.path }} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
    #     echo "--------------------------------------"
    #     echo "PRINT FROM OUTPUTS - SAME JOB"
    #     echo "--------------------------------------"
    #     echo "Root: ${{ needs.job1.outputs.ROOT_OUTPUT }}"
    #     echo "Project: ${{ needs.job1.outputs.PROJECT_OUTPUT }}"
    #     echo "Solution: ${{ needs.job1.outputs.SOLUTION_OUTPUT }}"
    #     echo "MySolution: ${{ needs.job1.outputs.mySoulution }}"

# test: making it dependent of previous step.
# -create outputs then -calls to those outputs

